### ISSUE TITLE
Requirements 

### ISSUE THREAD

**Issue by aaronvanoung** [Solobrosco/monitor-bot#2]
Our python development needs a requirements.txt to keep track of all of the libraries we are using.
When aaronvanoung pushed his changes to the Coms branch, he included a library I did not have.
Imagine if it was several hundred libraries.
Pip install helps us manage our python libraries. (like npm)

Make sure you have pip installed and create a requirements.txt.
Run main.py with no errors.
Document Steps in README.md
Push all changes to separate branch

**Comment by Solobrosco** [comment]
Going to create a new issue about selenium ^^

**Comment by Solobrosco** [comment]
https://stackoverflow.com/questions/13537901/python-equivalent-of-npm-or-rubygems/46020794

**Comment by Solobrosco** [comment]
There's an answer on that page talking about "pipenv" we could use that instead

**Comment by aaronvanoung** [comment]
okay that makes more sense so we can just add pipenv as another option
